### ISSUE TITLE
长句报错

### ISSUE THREAD

**Issue by kangqf** [ElaWorkshop/halosir#13]
遇到了很多 load 的错误，通过F12 调试之后发现 https://halo.xhacker.im/youdao/query/test 请求无响应，经本机 ping 不通该域名对应的IP，通过将该域名添加到代理规则解决，还是希望换个IP，以满足更多用户。

**Comment by kangqf** [comment]
抱歉，经查是自己的路由器的172网段的路由表设置错误，但是长句服务端报 `500`  确实存在。

**Comment by aquarhead** [comment]
使用 JSON API 应该没有什么广告的问题, 应该是之前的其他网络因素导致的, 现在应该修复了.
