### ISSUE TITLE
Wrong result when looping up multiple words

### ISSUE THREAD

**Issue by xhacker** [ElaWorkshop/halosir#6]
Steps:
0. Open Halo Word
1. Enter “polymorphic constants”

**Comment by xhacker** [comment]
<img width="420" alt="2016-08-21 2 34 05" src="https://cloud.githubusercontent.com/assets/1051813/17839910/55acca8c-67ac-11e6-85c4-e14832ad3ece.png">

**Comment by aquarhead** [comment]
iirc that's what 23402f249d270eb9fcbb48b5cb923e85cdd4477a was for.......
